#!/usr/bin/env bash
#Bash script that gives you information about the school file

name="school"
if [ -f "$name" ]; then
    echo "$name file exists"
else
    echo "$name file does not exist"
fi
if [ -s "$name" ]; then
    echo "$name file is empty"
else
    echo "$name file is not empty"
fi
if [ -f "$name" ]; then
    echo ""
else
    echo "$name is a regular file"
fi
